server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2console
  datasource:
    url: jdbc:h2:mem:database
    username: sa
    password:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false